name: flutter_map_supercluster
description: Very fast Marker clustering for flutter_map. Supports efficient adding/removing of Markers.
version: 5.0.0-dev.1
homepage: https://github.com/rorystephenson/flutter_map_supercluster
topics:
  - flutter-map
  - cluster

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  async: any
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_map: ^8.0.0
  flutter_map_marker_popup:
    git:
      url: https://github.com/joaovvrodrigues/flutter_map_marker_popup.git
      ref: upgrade_flutter_map_v8
  latlong2: ^0.9.1
  provider: ^6.1.2
  supercluster: ^3.1.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter